# Write the search results as Lean data files.
import json, sys, os
sys.path.insert(0, os.path.dirname(__file__))
from collections import defaultdict

def cells(cs): return "[" + ", ".join(f"({x}, {y})" for x, y in cs) + "]"
def ops(os): return "[" + ", ".join(k if d is None else f"{k} {d}" for k, d in os) + "]"
def entry(cs, f): return f"  ⟨{cells(cs)}, {f[0]}, {f[1]}, {ops(f[2])}⟩"

HEADER = """import ShapeAlgebra.Basic

-- Generated by python/make_lean_data.py. Each entry: a shape (cells), then a formula
-- that builds it: the strip direction, the strip length, and the list of steps.

open Dir Op

"""

def tables(maxn):
    w = json.load(open("python/witnesses_upto_10.json"))
    by_n = defaultdict(list)
    for e in w:
        if len(e["shape"]) <= maxn:
            by_n[len(e["shape"])].append((sorted(map(tuple, e["shape"])), e["formula"]))
    for n, es in sorted(by_n.items()):
        es.sort()
        body = ",\n".join(entry(cs, f) for cs, f in es)
        open(f"ShapeAlgebra/Data/Table{n}.lean", "w").write(
            HEADER + f"/-- A formula for each of the {len(es)} fixed polyominoes with {n} cells. -/\n"
            f"def table{n} : List (List Cell × Dir × Nat × List Op) := [\n{body}\n]\n")
        print(f"Table{n}.lean: {len(es)} entries")

def blocked():
    res = json.load(open("python/experiment_results.json"))
    from polys import normalize
    es = sorted((normalize(list(map(tuple, r["shape"]))), r["formula"]) for r in res)
    body = ",\n".join(entry(cs, f) for cs, f in es)
    open("ShapeAlgebra/Data/BlockedTable.lean", "w").write(
        HEADER + f"/-- The {len(es)} shapes with 11-14 cells where no cell can be the last one added,\n"
        "    each with a formula (from python/experiment.py) that holds at most one extra cell. -/\n"
        f"def blockedTable : List (List Cell × Dir × Nat × List Op) := [\n{body}\n]\n")
    print(f"BlockedTable.lean: {len(es)} entries")

tables(int(sys.argv[1])); blocked()
