import ShapeAlgebra.Basic

-- Generated by python/make_lean_data.py. Each entry: a shape (cells), then a formula
-- that builds it: the strip direction, the strip length, and the list of steps.

open Dir Op

/-- A formula for each of the 1 fixed polyominoes with 1 cells. -/
def table1 : List (List Cell × Dir × Nat × List Op) := [
  ⟨[(0, 0)], R, 1, []⟩
]
