import ShapeAlgebra.Basic

-- Generated by python/make_lean_data.py. Each entry: a shape (cells), then a formula
-- that builds it: the strip direction, the strip length, and the list of steps.

open Dir Op

/-- A formula for each of the 19 fixed polyominoes with 4 cells. -/
def table4 : List (List Cell × Dir × Nat × List Op) := [
  ⟨[(0, 0), (0, 1), (0, 2), (0, 3)], C, 4, []⟩,
  ⟨[(0, 0), (0, 1), (0, 2), (1, 0)], C, 3, [mirror R, add R, mirror R]⟩,
  ⟨[(0, 0), (0, 1), (0, 2), (1, 1)], C, 2, [add R, push C, add C]⟩,
  ⟨[(0, 0), (0, 1), (0, 2), (1, 2)], C, 3, [add R]⟩,
  ⟨[(0, 0), (0, 1), (1, 0), (1, 1)], R, 2, [add C, mirror C, add R, mirror C]⟩,
  ⟨[(0, 0), (0, 1), (1, 0), (2, 0)], R, 3, [mirror C, add C, mirror C]⟩,
  ⟨[(0, 0), (0, 1), (1, 1), (1, 2)], C, 2, [add R, add C]⟩,
  ⟨[(0, 0), (0, 1), (1, 1), (2, 1)], C, 2, [add R, add R]⟩,
  ⟨[(0, 0), (1, 0), (1, 1), (1, 2)], R, 2, [add C, add C]⟩,
  ⟨[(0, 0), (1, 0), (1, 1), (2, 0)], R, 2, [add C, push R, add R]⟩,
  ⟨[(0, 0), (1, 0), (1, 1), (2, 1)], R, 2, [add C, add R]⟩,
  ⟨[(0, 0), (1, 0), (2, 0), (2, 1)], R, 3, [add C]⟩,
  ⟨[(0, 0), (1, 0), (2, 0), (3, 0)], R, 4, []⟩,
  ⟨[(0, 1), (0, 2), (1, 0), (1, 1)], C, 2, [mirror R, add R, add C, mirror R]⟩,
  ⟨[(0, 1), (1, 0), (1, 1), (1, 2)], R, 2, [add C, mirror R, add C, mirror R]⟩,
  ⟨[(0, 1), (1, 0), (1, 1), (2, 0)], R, 2, [mirror R, add C, add R, mirror R]⟩,
  ⟨[(0, 1), (1, 0), (1, 1), (2, 1)], C, 2, [add R, mirror C, add R, mirror C]⟩,
  ⟨[(0, 1), (1, 1), (2, 0), (2, 1)], R, 3, [mirror R, add C, mirror R]⟩,
  ⟨[(0, 2), (1, 0), (1, 1), (1, 2)], C, 3, [mirror C, add R, mirror C]⟩
]
