import ShapeAlgebra.Basic

-- Generated by python/make_lean_data.py. Each entry: a shape (cells), then a formula
-- that builds it: the strip direction, the strip length, and the list of steps.

open Dir Op

/-- A formula for each of the 2 fixed polyominoes with 2 cells. -/
def table2 : List (List Cell × Dir × Nat × List Op) := [
  ⟨[(0, 0), (0, 1)], C, 2, []⟩,
  ⟨[(0, 0), (1, 0)], R, 2, []⟩
]
