import ShapeAlgebra.Basic

-- Generated by python/make_lean_data.py. Each entry: a shape (cells), then a formula
-- that builds it: the strip direction, the strip length, and the list of steps.

open Dir Op

/-- A formula for each of the 6 fixed polyominoes with 3 cells. -/
def table3 : List (List Cell × Dir × Nat × List Op) := [
  ⟨[(0, 0), (0, 1), (0, 2)], C, 3, []⟩,
  ⟨[(0, 0), (0, 1), (1, 0)], R, 2, [mirror C, add C, mirror C]⟩,
  ⟨[(0, 0), (0, 1), (1, 1)], C, 2, [add R]⟩,
  ⟨[(0, 0), (1, 0), (1, 1)], R, 2, [add C]⟩,
  ⟨[(0, 0), (1, 0), (2, 0)], R, 3, []⟩,
  ⟨[(0, 1), (1, 0), (1, 1)], R, 2, [mirror R, add C, mirror R]⟩
]
